---
- name: Create grafana folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/grafana"
    state: directory
    mode: 0755
  become: false

- name: Copy grafana docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/grafana-docker-compose.yml.j2
    dest: "{{ config_dir }}/grafana/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart grafana

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure grafana is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/grafana/"
    build: false
  become: false