---
- hosts: all
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - default.config.yml
        - config.yml
  roles: 
   - common

- hosts: all
  tasks:
    - name: debug services
      debug:
        msg: "{{ services }}"
    - name: include roles mentioned in services
      include_role:
        name: "{{ item }}"
      loop: "{{ services }}"
      when: services is defined