- hosts: pi
  vars_files:
    - env_vars.yml
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm
    - docker_compose_service
    - mqtt