- hosts: main
  vars_files:
    - env_vars.yml
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
  roles:
    - common
    - role: geerlingguy.pip
    - role: geerlingguy.docker_arm
    - docker_compose_service
    - mqtt
    - { role: data_monitor, action: install }
    - homebridge
    - node_red
    - pihole
    - { role: influx, action: install }
    - docker_volume_backup