- name: /etc/docker/compose/node-red
  file:
    path: /etc/docker/compose/node-red
    state: directory
    owner: root
    group: root
  become: true

- name: docker compose file for node-red
  template:
    src: docker-compose.yml
    dest: /etc/docker/compose/node-red/docker-compose.yml
  become: true

- name: docker-compose@node-red.service restarted
  systemd:
    name: docker-compose@node-red
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true

- include: update_config.yml
  when: update_config_files