- name : copy settings
  template:
    src: "{{ config_files_path }}/node-red-settings.js"
    dest: /var/lib/docker/volumes/node-red/_data/settings.js
  become: true

- name: docker-compose@node-red.service started
  systemd:
    name: docker-compose@node-red
    state: restarted
  become: true