---
# Sets up cron to run the iq envoy monitor script
- name: Configure IQ Envoy Cron
  cron:
    name: iq envoy influxdb reporting
    job: 'cd ~/monitoring_scripts && python record_envoy_data.py'
# Sets up cron to run the speed test monitor script
- name: Configure Speedtest Cron
  cron:
    name: isp speedtest reporting
    job: 'cd ~/monitoring_scripts && python record_isp_speed.py'
    minute: "0,10,20,30,40,50"