- name: /etc/docker/compose
  file:
    path: /etc/docker/compose/mosquitto
    state: directory
    owner: root
    group: root
  become: true

- name: docker compose file for mosquitto
  template:
    src: docker-compose.yml
    dest: /etc/docker/compose/mosquitto/docker-compose.yml
  become: true

- name: docker-compose@mosquitto.service started
  systemd:
    name: docker-compose@mosquitto
    state: started
    daemon_reload: yes
    enabled: yes
  become: true