- name: apt nginx
  apt:
    pkg:
      - 'nginx'
  become: true

- name: Load vhost mapping.
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - "{{ config_files_path }}/vhost_map.yml"
  
- name: Site file for vhost proxies
  template:
    src: nginx-proxy-vhosts.j2
    dest: /etc/nginx/sites-available/proxy-vhosts
  become: true
  notify: 
    - Restart nginx

- name: Symlink the site file
  file:
    src: /etc/nginx/sites-available/proxy-vhosts
    dest: /etc/nginx/sites-enabled/proxy-vhosts
    owner: root
    group: root
    state: link
  become: true
  notify: 
    - Restart nginx