---
- name: 'rename the host'
  hostname:
    name: rileypi.local
  become: true
- name: 'install basic dependencies'
  apt:
    name: ['avahi-daemon', 'vim', 'git', 'python-pip']
    state: present
  become: true
