- hosts: pi
  vars_files:
    - ../env_vars.yml

  tasks:
    - name: copy monitoring-scripts config to docker volume
      template: 
        src: config.yml.j2 
        dest: /var/lib/docker/volumes/monitoring-scripts/_data/config.yml
      become: true

    - name: monitoring-scripts > restart service
      systemd:
        name: monitoring-scripts
        state: restarted
        daemon_reload: yes
        enabled: yes
      become: true