- hosts: pi
  vars_files:
    - ../env_vars.yml

  tasks:
    - name: update monitoring-scripts code
      git:
        repo: "{{ monitoring_scripts_repo }}"
        dest: ~/monitoring_scripts
        force: yes

    - name: create monitoring-scripts image
      docker_image:
        build:
          path: ~/monitoring_scripts
          nocache: yes
          pull: no
        name: monitoring-scripts
        force_absent: yes
        source: build

    - name: stop monitoring-scripts service
      systemd:
        name: monitoring-scripts
        state: stopped
        daemon_reload: yes
        enabled: yes
      become: true

    - name: remove monitoring-scripts container
      docker_container:
        name: monitoring-scripts
        state: absent

    - name: start monitoring-scripts service
      systemd:
        name: monitoring-scripts
        state: started
        daemon_reload: yes
        enabled: yes
      become: true

    - name: Prune old containers and images
      docker_prune:
        containers: yes
        images: yes