- hosts: pi
  vars_files:
    - ../env_vars.yml
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm

  tasks:
    - name: monitoring-scripts > systemd service definition
      template:
        src: monitoring-scripts.service.j2
        dest: /etc/systemd/system/monitoring-scripts.service
        owner: root
      become: true

    - name: monitoring-scripts > docker volume
      docker_volume:
        name: monitoring-scripts

    - name: update monitoring-scripts code
      git:
        repo: "{{ monitoring_scripts_repo }}"
        dest: ~/monitoring_scripts
        force: yes

    - name: copy monitoring-scripts config
      template: src=config.yml.j2 dest=~/monitoring_scripts/config.yml

    - name: create monitoring-scripts image
      docker_image:
        build:
          path: ~/monitoring_scripts/
        name: monitoring-scripts
        source: build

    - name: stop monitoring-scripts service
      systemd:
        name: monitoring-scripts
        state: stopped
        daemon_reload: yes
        enabled: yes
      become: true

    - name: remove monitoring-scripts container
      docker_container:
        name: monitoring-scripts
        state: absent

    - name: start monitoring-scripts service
      systemd:
        name: monitoring-scripts
        state: started
        daemon_reload: yes
        enabled: yes
      become: true