- name: 'install bcryptjs'
  npm:
    name: bcryptjs
    state: present
    path: ~/
  become: true

- name: 'hash the node-red admin password'
  shell: node -e "console.log(require('bcryptjs').hashSync(process.argv[1], 8));" {{node_red_password}}
  register: node_red_pw_hash

- set_fact:
    node_red_pw_hash={{ node_red_pw_hash.stdout }}

- name: 'write settings.js'
  template:
    src: settings.js.j2
    dest: /home/nodered/.node-red/settings.js
    owner: nodered
  become: true

- debug: var=node_red_pw_hash
  run_once: true