---
# install influxdb
- name: install node-red-contrib-influxdb
  npm:
    name: node-red-contrib-influxdb
    path: /home/nodered/.node-red
  become: true

- name: install node-red-contrib-alexa-home
  npm:
    name: node-red-contrib-alexa-home
    path: /home/nodered/.node-red
  become: true

- name: Ensure nodered owns it's node_modules
  file:
    path: /home/nodered/.nodered
    state: directory
    recurse: yes
    owner: nodered
    group: nodered