- name: /etc/docker/compose/homebridge
  file:
    path: /etc/docker/compose/homebridge
    state: directory
    owner: root
    group: root
  become: true

- name: docker compose file for homebridge
  template:
    src: docker-compose.yml
    dest: /etc/docker/compose/homebridge/docker-compose.yml
  become: true

- name: docker-compose@homebridge.service started
  systemd:
    name: docker-compose@homebridge
    state: started
    daemon_reload: yes
    enabled: yes
  become: true

- include: update_config.yml
  when: update_config_files