- name: Restart service homebridge, in all cases
  service:
    name: homebridge
    state: restarted
  become: true
- name: Enable service homebridge
  systemd:
    name: homebridge
    enabled: true
  become: true
