- name: copy repo code to /etc/docker/compose/data-monitor
  git:
    repo: "{{ monitoring_scripts_repo }}"
    dest: /etc/docker/compose/data-monitor
    force: yes
  become: true
  notify: 
    - remove data-monitor image
    - restart data-monitor