---
- name: Set the hostname
  ansible.builtin.import_tasks: hostname.yml
- name: Ensure apt cache is up to date.
  ansible.builtin.import_tasks: apt-update.yml
- name: Set up Docker
  ansible.builtin.import_tasks: docker.yml