- name: /etc/docker/compose/influx
  file:
    path: /etc/docker/compose/influx
    state: directory
    owner: root
    group: root
  become: true

- name: docker compose file for influx
  template:
    src: docker-compose.yml
    dest: /etc/docker/compose/influx/docker-compose.yml
  become: true

- name: docker-compose@influx.service restarted
  systemd:
    name: docker-compose@influx
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true