---
  # install the homebridge-mqtt package
  # update homebridge config JSON to add mqtt as a platform

  - name: copy the config update script
    copy:
      src: config_script.py
      dest: /var/lib/homebridge/mqtt_config.py
      owner: homebridge
      group: homebridge
    become: true

  - name: run config update script
    command: python mqtt_config.py
    args:
      chdir: /var/lib/homebridge
    become: true
