- name: /etc/docker/compose/pihole
  file:
    path: /etc/docker/compose/pihole
    state: directory
    owner: root
    group: root
  become: true

- name: docker compose file for pihole
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/pihole/docker-compose.yml
  become: true

- name: docker-compose@pihole.service restarted
  systemd:
    name: docker-compose@pihole
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true